import React, {useEffect, useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Activity, AlertTriangle, BrainCircuit, CheckCircle2, ChevronRight, Clock3, Cpu, FileSearch, Globe2, KeyRound, Laptop, LockKeyhole, Network, Search, ShieldCheck, Usb, XCircle} from 'lucide-react'
import './styles.css'

const API='http://localhost:8000/api'

type Evidence={event_id:string;timestamp:string;statement:string;kind:string}
type Factor={rule_id:string;title:string;score:number;reason:string}
type Prediction={experimental:boolean;prediction:string;confidence:number;signals:string[];rationale:string;disclaimer:string}
type Incident={incident_id:string;title:string;severity:string;risk_score:number;status:string;start:string;end:string;event_ids:string[];observed:Evidence[];inferred:Evidence[];unknown:Evidence[];factors:Factor[];prediction:Prediction}

type Tab='overview'|'away'|'access'|'usb'|'changes'|'ask'|'incident'|'prediction'

function App(){
 const [incident,setIncident]=useState<Incident|null>(null)
 const [tab,setTab]=useState<Tab>('overview')
 const [question,setQuestion]=useState('What happened while I was away?')
 const [answer,setAnswer]=useState<any>(null)
 const [loading,setLoading]=useState(true)
 useEffect(()=>{fetch(`${API}/incidents/INC-001`).then(r=>r.json()).then(x=>{setIncident(x);setLoading(false)})},[])
 async function ask(){const r=await fetch(`${API}/investigate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,incident_id:'INC-001'})});setAnswer(await r.json());setTab('ask')}
 const failedLogins=useMemo(()=>incident?.observed.filter(e=>e.statement.toLowerCase().includes('failed')||e.statement.toLowerCase().includes('authentication')).length||0, [incident])
 if(loading)return <div className="loading"><div><div className="spinner"/><span>Loading local security workspace…</span></div></div>
 const nav=[
  ['overview','Is Everything Okay?',ShieldCheck],['away','When I Was Away',Clock3],['access','Access Attempts',KeyRound],['usb','USB Activity',Usb],['changes','What Changed?',FileSearch],['ask','Ask My Computer',BrainCircuit],['incident','Incidents',AlertTriangle],['prediction','Attack Prediction',BrainCircuit]
 ] as const
 return <div className="app">
  <aside className="sidebar">
   <div className="brand"><div className="brandmark"><ShieldCheck size={21}/></div><div><strong>LOCAL SECURITY</strong><span>INTELLIGENCE BUILD</span></div></div>
   <div className="status"><span className="pulse"/> LOCAL MODE <b>WIP</b></div>
   <nav>{nav.map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={16}/><span>{label}</span>{id==='incident'&&<em>1</em>}</button>)}</nav>
   <div className="sidebarBottom"><div className="device"><Laptop size={15}/><div><b>desktop-01</b><span>Telemetry online</span></div></div><div className="build">v0.1.0-local · pre-release</div></div>
  </aside>
  <main>
   <header className="topbar"><div><span className="crumb">LOCAL WORKSPACE / {tab.toUpperCase()}</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="topmeta"><span><span className="greenDot"/> Local telemetry</span><span className="buildTag">WORK IN PROGRESS</span></div></header>
   {tab==='overview'&&<Overview incident={incident!} onTab={setTab} failedLogins={failedLogins}/>} 
   {tab==='away'&&<Away incident={incident!} />}
   {tab==='access'&&<Access incident={incident!}/>} 
   {tab==='usb'&&<UsbView incident={incident!}/>} 
   {tab==='changes'&&<Changes incident={incident!}/>} 
   {tab==='incident'&&<IncidentView incident={incident!}/>} 
   {tab==='prediction'&&<Prediction incident={incident!}/>} 
   {tab==='ask'&&<Ask question={question} setQuestion={setQuestion} ask={ask} answer={answer} setAnswer={setAnswer}/>} 
  </main>
 </div>
}

function Overview({incident,onTab,failedLogins}:{incident:Incident;onTab:(t:Tab)=>void;failedLogins:number}){return <>
 <section className="heroGrid"><div className="heroCard"><div className="eyebrow">SECURITY STATUS</div><div className="statusRow"><div className="bigCheck"><CheckCircle2 size={30}/></div><div><h2>Your computer looks okay.</h2><p>No critical activity is currently detected. One reconstructed incident needs review.</p></div></div><div className="heroActions"><button onClick={()=>onTab('away')}>See what happened while away <ChevronRight size={15}/></button><button className="ghost" onClick={()=>onTab('incident')}>Open incident</button></div></div><div className="scoreCard"><span>RECONSTRUCTED RISK</span><strong>{incident.risk_score}<small>/100</small></strong><label>{incident.severity} · {incident.status}</label><div className="scorebar"><i style={{width:`${incident.risk_score}%`}}/></div></div></section>
 <section className="cards four"><Stat icon={KeyRound} title="Access attempts" value={failedLogins||4} note="failed in demo window" onClick={()=>onTab('access')}/><Stat icon={Usb} title="USB activity" value="1" note="device observed" onClick={()=>onTab('usb')}/><Stat icon={Network} title="Network" value="1" note="external connection" onClick={()=>onTab('incident')}/><Stat icon={FileSearch} title="Changes" value="2" note="persistence-related" onClick={()=>onTab('changes')}/></section>
 <section className="twoCol"><div className="panel"><PanelTitle icon={Activity} title="Meaningful activity" action="Open timeline" onClick={()=>onTab('incident')}/><Timeline incident={incident} compact/></div><div className="panel"><PanelTitle icon={BrainCircuit} title="Ask your computer"/><p className="panelLead">You don't need to understand security logs. Ask a question and investigate from the evidence.</p><div className="questionList"><button onClick={()=>onTab('away')}>What happened while I was away?<ChevronRight size={15}/></button><button onClick={()=>onTab('usb')}>What did my USB do?<ChevronRight size={15}/></button><button onClick={()=>onTab('access')}>Did anyone try to access me?<ChevronRight size={15}/></button></div></div></section>
 </>}
function Stat({icon:Icon,title,value,note,onClick}:{icon:any;title:string;value:string|number;note:string;onClick:()=>void}){return <button className="stat" onClick={onClick}><Icon size={17}/><span>{title}</span><strong>{value}</strong><small>{note}</small></button>}
function PanelTitle({icon:Icon,title,action,onClick}:{icon:any;title:string;action?:string;onClick?:()=>void}){return <div className="panelTitle"><div><Icon size={16}/><b>{title}</b></div>{action&&<button onClick={onClick}>{action}<ChevronRight size={13}/></button>}</div>}
function Timeline({incident,compact=false}:{incident:Incident;compact?:boolean}){const ev=compact?incident.observed.slice(0,5):incident.observed;return <div className="timeline">{ev.map((e,i)=><div className="event" key={e.event_id}><div className="eventTime">{new Date(e.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</div><div className="eventLine"><span className="eventDot"/></div><div className="eventBody"><b>{e.statement}</b><small>{e.event_id} · observed</small></div></div>)}</div>}
function Away({incident}:{incident:Incident}){return <><section className="context"><Clock3 size={17}/><div><b>Your away window</b><span>{new Date(incident.start).toLocaleTimeString()} → {new Date(incident.end).toLocaleTimeString()} · reconstructed from local telemetry</span></div></section><section className="twoCol"><div className="panel"><PanelTitle icon={Clock3} title="What happened while you were away?"/><Timeline incident={incident}/></div><div className="panel"><PanelTitle icon={ShieldCheck} title="Plain-language summary"/><div className="summary"><div className="summaryIcon"><AlertTriangle/></div><h3>Something unusual was observed.</h3><p>A USB device was connected, followed shortly by executable activity, an external network connection, and a persistence-related change. These events were correlated into one incident.</p><div className="callout"><b>Important</b><span>The evidence shows what the computer observed. It does not by itself prove who initiated the activity or malicious intent.</span></div></div></div></section></>}
function Access({incident}:{incident:Incident}){return <><section className="cards two"><div className="metricPanel"><span>AUTHENTICATION SIGNAL</span><strong>4</strong><p>failed attempts in the demo scenario</p></div><div className="metricPanel safe"><span>SUCCESSFUL REMOTE ACCESS</span><strong>0</strong><p>No successful remote session is represented in this demo dataset.</p></div></section><section className="panel"><PanelTitle icon={KeyRound} title="Access activity"/><div className="table"><div className="thead"><span>TIME</span><span>ACTIVITY</span><span>RESULT</span><span>SOURCE</span></div>{['03:17:02','03:17:05','03:17:08','03:17:11'].map((t,i)=><div className="tr" key={t}><span>{t}</span><span>Remote authentication attempt</span><span className="bad">FAILED</span><span>remote source</span></div>)}</div></section></>}
function UsbView({incident}:{incident:Incident}){return <><section className="panel"><PanelTitle icon={Usb} title="USB → activity chain"/><div className="chain"><Chain label="USB connected" time="12:15:03"/><Chain label="update-helper.exe started" time="12:15:08"/><Chain label="cmd.exe child process" time="12:15:09"/><Chain label="External connection" time="12:15:12"/><Chain label="Scheduled task created" time="12:15:15"/></div></section><section className="twoCol"><div className="panel"><PanelTitle icon={AlertTriangle} title="Why this matters"/><p className="panelLead">Individually, these events may have benign explanations. Together, their temporal and process relationships raise the reconstructed risk.</p><button className="primary" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>Open reconstructed incident <ChevronRight size={15}/></button></div><div className="panel"><PanelTitle icon={LockKeyhole} title="Evidence boundary"/><Evidence incident={incident}/></div></section></>}
function Chain({label,time}:{label:string;time:string}){return <div className="chainItem"><span className="chainDot"/><div><b>{label}</b><small>{time}</small></div></div>}
function Changes({incident}:{incident:Incident}){return <section className="twoCol"><div className="panel"><PanelTitle icon={FileSearch} title="Observed changes"/><div className="change"><b>Scheduled task persistence</b><span>System Update Check · observed after process execution</span></div><div className="change"><b>Startup entry modification</b><span>update.lnk · observed in user startup location</span></div></div><div className="panel"><PanelTitle icon={Activity} title="Correlation"/><p className="panelLead">The engine links the changes to nearby process activity rather than treating them as isolated alerts.</p><div className="miniScore">{incident.risk_score}<small>/100</small></div></div></section>}
function IncidentView({incident}:{incident:Incident}){return <><section className="incidentHeader"><div><div className="eyebrow">RECONSTRUCTED INCIDENT · {incident.incident_id}</div><h2>{incident.title}</h2><p>Potentially related activity reconstructed from local endpoint telemetry.</p></div><div className="pill">{incident.severity} · {incident.risk_score}/100</div></section><section className="twoCol"><div className="panel"><PanelTitle icon={Activity} title="Incident timeline"/><Timeline incident={incident}/></div><div className="panel"><PanelTitle icon={AlertTriangle} title="Risk factors"/>{incident.factors.map(f=><div className="factor" key={f.rule_id}><div><b>{f.title}</b><span>{f.reason}</span></div><strong>+{f.score}</strong></div>)}<div className="scorebar"><i style={{width:`${incident.risk_score}%`}}/></div></div></section><section className="panel"><PanelTitle icon={LockKeyhole} title="Evidence model"/><Evidence incident={incident}/></section></>}
function Evidence({incident}:{incident:Incident}){return <div className="evidenceGrid"><EvidenceCol title="OBSERVED" items={incident.observed.slice(0,4)}/><EvidenceCol title="INFERRED" items={incident.inferred}/><EvidenceCol title="UNKNOWN" items={incident.unknown}/></div>}
function EvidenceCol({title,items}:{title:string;items:Evidence[]}){return <div className="eCol"><label>{title}</label>{items.map(x=><p key={x.event_id}>{x.statement}</p>)}</div>}
function Prediction({incident}:{incident:Incident}){const p=incident.prediction;return <><section className="predictionHero"><div className="eyebrow">EXPERIMENTAL FEATURE</div><h2>Possible next-stage activity</h2><p>This view explores whether a reconstructed behavior chain can suggest what may come next.</p><div className="predictionValue"><BrainCircuit size={20}/><strong>{p.prediction}</strong><span>{p.confidence}% confidence</span></div></section><section className="twoCol"><div className="panel"><PanelTitle icon={Network} title="Signals used"/>{p.signals.map(s=><div className="signal" key={s}><CheckCircle2 size={14}/>{s}</div>)}<p className="panelLead">{p.rationale}</p></div><div className="panel warning"><PanelTitle icon={AlertTriangle} title="Prediction boundary"/><p>{p.disclaimer}</p><p>For the hackathon build this remains an experimental research surface, not an automated response authority.</p></div></section></>}
function Ask({question,setQuestion,ask,answer,setAnswer}:{question:string;setQuestion:(s:string)=>void;ask:()=>void;answer:any;setAnswer:(x:any)=>void}){return <section className="askLayout"><div className="panel askPanel"><PanelTitle icon={BrainCircuit} title="Ask your computer"/><p className="panelLead">Ask in normal language. The prototype retrieves the reconstructed incident and answers from the available evidence.</p><div className="chips"><button onClick={()=>setQuestion('What happened while I was away?')}>What happened while I was away?</button><button onClick={()=>setQuestion('What did the USB do?')}>What did the USB do?</button><button onClick={()=>setQuestion('Why was this flagged?')}>Why was this flagged?</button></div><textarea value={question} onChange={e=>setQuestion(e.target.value)} /><button className="primary full" onClick={ask}>Investigate <ChevronRight size={15}/></button></div>{answer?<div className="panel answerPanel"><div className="eyebrow">EVIDENCE-BACKED RESPONSE</div><h2>{answer.answer}</h2><p>{answer.risk}</p><div className="callout"><b>Boundary</b><span>{answer.limitations}</span></div><button className="ghostBtn" onClick={()=>setAnswer(null)}>Ask another question</button></div>:<div className="empty"><Search size={28}/><b>Ask something about this computer.</b><span>The answer panel will appear here after an investigation.</span></div>}</section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
